# Generated by Django 5.2.8 on 2025-12-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('LIFESTYLE', 'Lifestyle'), ('BUSINESS', 'Business'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('CODING', 'Coding'), ('PROGRAMMING', 'Programming'), ('FOOD', 'Food'), ('FASHION', 'Fashion'), ('SPORTS', 'Sports'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('CPLUSPLUS', 'C++'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SWIFT', 'Swift'), ('KOTLIN', 'Kotlin'), ('GO', 'Go'), ('RUST', 'Rust'), ('TYPESCRIPT', 'TypeScript'), ('PHP', 'PHP'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('DJANGO', 'Django'), ('FLASK', 'Flask'), ('REACT', 'React'), ('ANGULAR', 'Angular'), ('VUE', 'Vue.js'), ('NODEJS', 'Node.js'), ('SQL', 'SQL'), ('NOSQL', 'NoSQL'), ('MONGODB', 'MongoDB'), ('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_category', to='core.category_types')),
                ('tag', models.ManyToManyField(related_name='blog_posts_tags', to='core.tag_types')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
