# Generated by Django 5.2.8 on 2025-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(),
        ),
    ]
