# Generated by Django 5.2.8 on 2025-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='featured_article',
            field=models.BooleanField(default=False),
        ),
    ]
