# Generated by Django 5.2.8 on 2025-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_post_featured_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-searched_at']},
        ),
        migrations.AlterField(
            model_name='tag_types',
            name='Tag',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('DJANGO', 'Django'), ('REACT', 'React')], max_length=50, unique=True),
        ),
    ]
